=== mariru27/Web-Technology/Rusu_Marina_222_Tema2/DiplomaDeBacalaureat.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT DIPLOMABAC (ELEV*)>
<!ELEMENT ELEV (PERSOANA,CIF,SCOALAABSOLVITA,ELIBERAREADIPLOMEI,SITUATIEBAC)>
<!ATTLIST ELEV cnp CDATA #REQUIRED >
<!ELEMENT PERSOANA (SERIE,NR,NUME,PRENUME) >
<!ELEMENT SERIE (#PCDATA)>
<!ELEMENT NR (#PCDATA) >
<!ELEMENT NUME (#PCDATA)>
<!ELEMENT PRENUME (#PCDATA) >
<!ELEMENT CIF (#PCDATA)>
<!ELEMENT SCOALAABSOLVITA (DENUMIRE,LOCALITATE,FILIERA,PROFILUL,SPECIALIZAREA,ANUL) >
<!ELEMENT DENUMIRE (#PCDATA) >
<!ELEMENT LOCALITATE (#PCDATA)>
<!ELEMENT FILIERA (#PCDATA) >
<!ELEMENT PROFILUL (#PCDATA) >
<!ELEMENT SPECIALIZAREA (#PCDATA) >
<!ELEMENT ANUL (#PCDATA) >
<!ATTLIST ELIBERAREADIPLOMEI NrDiploma CDATA #REQUIRED >
<!ELEMENT ELIBERAREADIPLOMEI (DENUMIRE,SESIUNEA,ANUL,LOCALITATE,JUDET,DATA) >
<!ELEMENT SESIUNEA (#PCDATA) >
<!ELEMENT DENUMLOCALITATEAIRE (#PCDATA) >
<!ELEMENT JUDET (#PCDATA) >
<!ELEMENT DATA (#PCDATA) >
<!ELEMENT SITUATIEBAC (LOCALITATE,JUDET,SESIUNE,ANUL,REZULTATEBAC) >
<!ELEMENT REZULTATEBAC (DISCIPLINAEXAMEN*,MEDIE) >
<!ELEMENT MEDIE (#PCDATA) >
<!ELEMENT SESIUNE (#PCDATA) >
<!ELEMENT DISCIPLINAEXAMEN (DISCIPLINA,NOTA) >
<!ELEMENT DISCIPLINA (#PCDATA) >
<!ELEMENT NOTA (#PCDATA) >

=== mariru27/Web-Technology/Rusu_Marina_222_Tema2/Elevi-validate-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE DIPLOMABAC SYSTEM "DiplomaDeBacalaureat.dtd">

<DIPLOMABAC>
    <ELEV cnp="1234567890122">
        <PERSOANA>
            <SERIE>AB</SERIE>
            <NR>334</NR>
            <NUME>Mihai</NUME>
            <PRENUME>Valeriu</PRENUME>
        </PERSOANA>
        <CIF>1245658</CIF>
        <SCOALAABSOLVITA>
            <DENUMIRE>Stefan Cel Mare</DENUMIRE>
            <LOCALITATE>Iasi </LOCALITATE>
            <FILIERA>Teoretica</FILIERA>
            <PROFILUL>Umanist</PROFILUL>
            <SPECIALIZAREA>Filologie</SPECIALIZAREA>
            <ANUL>2010</ANUL>
        </SCOALAABSOLVITA>
        <ELIBERAREADIPLOMEI NrDiploma="32">
            <DENUMIRE>Colegiul National din Iasi</DENUMIRE>
            <SESIUNEA>iunie-lulie</SESIUNEA>
            <ANUL>2010</ANUL>
            <LOCALITATE>Iasi</LOCALITATE>
            <JUDET>Iasi</JUDET>
            <DATA>2010-07-24</DATA>
        </ELIBERAREADIPLOMEI>
        <SITUATIEBAC>
            <LOCALITATE>Iasi</LOCALITATE>
            <JUDET>Iasi</JUDET>
            <SESIUNE>iunie-iulie</SESIUNE>
            <ANUL>2010</ANUL>
            <REZULTATEBAC>
                <DISCIPLINAEXAMEN>
                    <DISCIPLINA>matematica</DISCIPLINA>
                    <NOTA>10</NOTA>
                </DISCIPLINAEXAMEN>
                <DISCIPLINAEXAMEN>
                    <DISCIPLINA>romana</DISCIPLINA>
                    <NOTA>10</NOTA>
                </DISCIPLINAEXAMEN>
                <DISCIPLINAEXAMEN>
                    <DISCIPLINA>engleza</DISCIPLINA>
                    <NOTA>10</NOTA>
                </DISCIPLINAEXAMEN>
                <MEDIE>10</MEDIE>
            </REZULTATEBAC>
        </SITUATIEBAC>
    </ELEV>
    
    <ELEV cnp="1224567890122">
        <PERSOANA>
            <SERIE>AP</SERIE>
            <NR>23441</NR>
            <NUME>Mihaela</NUME>
            <PRENUME>Popescu</PRENUME>
        </PERSOANA>
        <CIF>234452</CIF>
        <SCOALAABSOLVITA>
            <DENUMIRE>Mircea Eliade</DENUMIRE>
            <LOCALITATE>Iasi</LOCALITATE>
            <FILIERA>Teoretica</FILIERA>
            <PROFILUL>Umanist</PROFILUL>
            <SPECIALIZAREA>Filologie</SPECIALIZAREA>
            <ANUL>2015</ANUL>
        </SCOALAABSOLVITA>
        <ELIBERAREADIPLOMEI>
            <DENUMIRE>Colegiul Mircea Eliade</DENUMIRE>
            <SESIUNEA>iunie-iulie</SESIUNEA>
            <ANUL>2015</ANUL>
            <LOCALITATE>Iasi</LOCALITATE>
            <JUDET>Iasi</JUDET>
            <DATA>2015-07-29</DATA>
        </ELIBERAREADIPLOMEI>
        <SITUATIEBAC>
            <LOCALITATE>Iasi</LOCALITATE>
            <JUDET>Iasi</JUDET>
            <SESIUNE>iunie-iulie</SESIUNE>
            <ANUL>2015</ANUL>
            <REZULTATEBAC>
                <DISCIPLINAEXAMEN>
                    <DISCIPLINA>romana</DISCIPLINA>
                    <NOTA>6</NOTA>
                </DISCIPLINAEXAMEN>
                <DISCIPLINAEXAMEN>
                    <DISCIPLINA>matematica</DISCIPLINA>
                    <NOTA>9</NOTA>
                </DISCIPLINAEXAMEN>
                <DISCIPLINAEXAMEN>
                    <DISCIPLINA>informatica</DISCIPLINA>
                    <NOTA>10</NOTA>
                </DISCIPLINAEXAMEN>
                <DISCIPLINAEXAMEN>
                    <DISCIPLINA>engleza</DISCIPLINA>
                    <NOTA>9</NOTA>
                </DISCIPLINAEXAMEN>
                <MEDIE>8.5</MEDIE>
            </REZULTATEBAC>
        </SITUATIEBAC>
    </ELEV>
</DIPLOMABAC>
